# Generated by Django 5.2 on 2025-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "permissions": [("can_manage_merchants", "Can manage merchants")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True, verbose_name="last activity"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("MERCHANT", "Merchant"),
                    ("ADMIN", "Administrator"),
                ],
                default="CLIENT",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
